name: Run tests & Get code coverage report
on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
    - name: Copy JaCoCo HTML report
      run: mkdir reports && cp target\site\jacoco\index.html reports

  upload-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
      - name: Upload coverage report
        with:
          name: coverage-report
          path: reports
